version: "3.9"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  api:
    build: .
    image: gestion_consultas_api
    command: bash -c "
      while !</dev/tcp/postgres/5432; do sleep 1; done;
      python manage.py migrate --noinput
      && python manage.py collectstatic --noinput
      && python manage.py runserver 0.0.0.0:8000
      && daphne -b 0.0.0.0 -p 8000 gestion_consultas.asgi:application
      "
    expose:
      - "8000"
    volumes:
      - .:/code
      - static:/code/static
      - media:/code/media
    depends_on:
      - postgres
      - redis

  celery_worker:
    image: gestion_consultas_api
    command: celery -A gestion_consultas worker -l INFO
    volumes:
      - .:/code

  celery_beat:
    image: gestion_consultas_api
    command: celery -A gestion_consultas beat -l INFO
    volumes:
      - .:/code

  nginx:
    build: ./nginx
    image: gestion_consultas_api_nginx
    ports:
      - "8080:80"
    volumes:
      - static:/code/static
      - media:/code/media
    depends_on:
      - api

volumes:
  local_postgres_data:
  local_postgres_data_backups:
  redis:
  static:
  media:
